### ISSUE TITLE
Search engines and server-side translation

### ISSUE THREAD

**Issue by jtheisen** [locize/locizer#1]
Locizer is purely client-side, and I really like the approach. The only pain point is that search engines will only ever see the original language. Static sites for which Locizer shines often also benefit from translated search indexing.

Since Locizer can be used with any server-side rendering technology, it would be great to have some solution for that problem that again works with any such technology.

I'm thinking about some server-side reverse proxy that changes the html. As far as I can see, for largely static sites, the amount of information that Locizer has should only be roughly what comes over the wire in the form of html (plus the translations, of course).

Even if that process isn't completely compatible, we only need it for search indexing. Human visitors would still get served the original html and get Locizer to translate it in the browser.

I'd love to have some feedback or pointers to potentially already occurred discussions about this topic.

**Comment by jamuhl** [comment]
Agree with you…would be nice to have some similar solution for serverside rendering to help with SEO.

Current options would be using next.js / gatsby for react or nuxt.js for vue…but for every static site generation as you mention a solution will be harder to be created…there is basically no universal way of doing it.

A solution option could be a reverse proxy - currently there is no plan to add such a solution to our offering.

**Comment by jamuhl** [comment]
using https://github.com/locize/locizify in a node.js based reverse proxy might be an option...

**Comment by jtheisen** [comment]
Locizify operates on DOM stuff, which I believe isn't there in a usual node setup. So my initial feel would be that this isn't so straight-forward. But my expertise here is very limited - if you have something more to say, I'd be interested.

**Comment by jamuhl** [comment]
Well you need to parse DOM anyway and exchange content found with translations - locizify already does this -> "just" would need an option to read from string (html source) and render back to translated string instead of replacing virtual dom -> so content in other languages could be generated and cached for next requests.

locizer does nothing - just gives you the translation files based on language.

**Comment by jtheisen** [comment]
Really, locizify parses html? Why? Why does it not use the browser's parser? Seems hard to believe, are you sure?

(I know I confused locizer with locizify initially.)

**Comment by jamuhl** [comment]
It uses vdom to change current content with translations. It might be complexer as it seems...doing the merged nodes, segment replacement, listening for dom changes, bind mutation observers,...

**Comment by jtheisen** [comment]
Yes, but all of that is still way easier than parsing html, which is a nightmare (because it's often bad) - and browsers are basically the only pieces of software that are good at it.

**Comment by jamuhl** [comment]
vdom: initial html -> vdom (is parsing html) but for sure using that vdom implementation is simpler than building something yourself

**Comment by jtheisen** [comment]
Why does it not build the vdom from the real dom? By the time the script runs, the browser has parsed the page's html already.

**Comment by jamuhl** [comment]
it actually does that...https://github.com/i18next/i18nextify/blob/master/src/renderer.js#L25

but somewhere we also parse html string https://github.com/i18next/i18nextify/blob/master/src/localize.js#L264 (to parse translations containing html)

**Comment by jtheisen** [comment]
That's why I think you can't (easily, directly) use it server-side: There's no browser that can do the parsing for you.

In any case, this ticket is kind of in the wrong project and was more a question anyway. Should I ever do something in this direction, I'll contribute.

**Comment by jamuhl** [comment]
Like said one can parse vdom from string -> so a solution might be a mode that created static files...reading the html files...might be look into this in "far" future.
