### ISSUE TITLE
loadAll callback is never called

### ISSUE THREAD

**Issue by y3lousso** [locize/locizer#2]
## 🐛 Bug Report

The loadAll function fetch the API but never runs the callback.
Using locizer@3.3.4

## To Reproduce

- Follow the vue-i18n integration tutorial at: https://docs.locize.com/integration/instrumenting-your-code
- Use loadAll -> callback is never called
- Replace it with load -> it works

## Expected behavior

The callback should be called after the API data has been fetched.

## Your Environment

Node 16 Npm 8

**Comment by adrai** [comment]
It may be your projectId is wrong, or you've no published translations.
We just released v3.3.5 that should handle better that error scenario.
Can you verify?

**Comment by adrai** [comment]
If v3.3.5 does not fix it, please provide a reproducible example or send the code to support@locize.com

**Comment by y3lousso** [comment]
It works as expected, thanks for the quick fix 😄
